import { ReactNode } from "react";
import "../styles/globals.css";
import "../styles/style.css";
import { Control } from "../components/Control";
import { fetchTopics } from "@/data/DataControl";

export const metadata = {
  title: "Web tutorial",
  description: "Generated by egoing",
};

// 기본 레이아웃 컴포넌트
export default async function RootLayout({ children }: { children: ReactNode }) {
  const topics = await fetchTopics();
  // 콘솔에 출력
  console.log("page/layout.js/topics", topics);
  return (
    <html>
      <body className="bg-gray font-Pretendard">
        <div
          id="wrap"
          className="max-w-[1200px] h-[100vh] mx-auto flex items-center justify-center flex-col text-white text-center"
        >
          <main className="py-2 mb-5 w-full">{children}</main>
          <Control />
        </div>
      </body>
    </html>
  );
}
